version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: myntra_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: myntra  # Set database name
      POSTGRES_USER: postgres  # Set database user
      POSTGRES_PASSWORD: pass123  # Set database password
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Persistent storage for database

  nginx:
    image: nginx:latest
    build: ./nginx  # Path to your Nginx configuration directory (optional)
    ports:
      - "80:80"  # Map container port 80 to host port 80
    volumes:
      - ./app/static:/usr/share/nginx/html/static/  # Map static files (optional)
    depends_on:
      - web

volumes:
  postgres_data: {}  # Define named volume for postgres data
